#!/usr/bin/env python3
"""Fix invalid/colliding client IDs in offline wandb run files.

NOTE: The script is generated by claude code and I only verified it works e2e manually.
It should work with all recent wandb sdks because the id generation logic
is not importing from sdk and calls secrets.choice directly.

If you got proto version error, try upgrade proto 
    pip install -U "protobuf>=6.31.1"

Usage ... by claude code

This script fixes the "Invalid Client ID digest" error that can occur when syncing
offline runs created by older SDK versions where random.seed() caused ID collisions.

The fix (PR #11039) now uses a dedicated Random() instance, but users with existing
offline runs have invalid IDs baked into their .wandb files.
Fix PR: https://github.com/wandb/wandb/pull/11039

Usage:
    # Single file
    python fix_offline_run_client_ids.py ./wandb/offline-run-.../run-xxx.wandb

    # Preview changes without modifying
    python fix_offline_run_client_ids.py --dry-run ./wandb/offline-run-.../run-xxx.wandb

    # Process all offline runs in a directory (NOT tested!)
    python fix_offline_run_client_ids.py --dir ./wandb

The script creates a backup (.wandb.backup) before modifying any files. (Yeah it does)
"""

import argparse
import os
import re
import secrets
import shutil
import struct
import sys
import zlib
from string import ascii_lowercase, digits
from typing import Optional

from wandb.proto import wandb_internal_pb2

# Constants from wandb/sdk/internal/datastore.py
LEVELDBLOG_HEADER_LEN = 7
LEVELDBLOG_BLOCK_LEN = 32768
LEVELDBLOG_DATA_LEN = LEVELDBLOG_BLOCK_LEN - LEVELDBLOG_HEADER_LEN

LEVELDBLOG_FULL = 1
LEVELDBLOG_FIRST = 2
LEVELDBLOG_MIDDLE = 3
LEVELDBLOG_LAST = 4

LEVELDBLOG_HEADER_IDENT = b":W&B"
LEVELDBLOG_HEADER_MAGIC = 0xBEE1
LEVELDBLOG_HEADER_VERSION = 0

_ID_CHARS = f"{ascii_lowercase}{digits}"


def generate_id(length: int = 128) -> str:
    """Generate a cryptographically secure random ID."""
    return "".join(secrets.choice(_ID_CHARS) for _ in range(length))


def _strtobytes(x: str) -> bytes:
    if isinstance(x, bytes):
        return x
    return bytes(x, "iso8859-1")


class DataStoreReader:
    """Read records from a .wandb file (leveldb log format)."""

    def __init__(self, fname: str):
        self._fname = fname
        self._fp = open(fname, "rb")
        self._index = 0
        self._size_bytes = os.stat(fname).st_size

        # Precompute CRC bases for each record type
        self._crc = [0] * (LEVELDBLOG_LAST + 1)
        for x in range(1, LEVELDBLOG_LAST + 1):
            self._crc[x] = zlib.crc32(_strtobytes(chr(x))) & 0xFFFFFFFF

        self._read_header()

    def _read_header(self) -> None:
        header = self._fp.read(LEVELDBLOG_HEADER_LEN)
        if len(header) != LEVELDBLOG_HEADER_LEN:
            raise ValueError(f"Invalid header length: {len(header)}")
        ident, magic, version = struct.unpack("<4sHB", header)
        if ident != LEVELDBLOG_HEADER_IDENT:
            raise ValueError(f"Invalid header ident: {ident}")
        if magic != LEVELDBLOG_HEADER_MAGIC:
            raise ValueError(f"Invalid header magic: {magic:#x}")
        if version != LEVELDBLOG_HEADER_VERSION:
            raise ValueError(f"Invalid header version: {version}")
        self._index += LEVELDBLOG_HEADER_LEN

    def _scan_record(self) -> Optional[tuple]:
        header = self._fp.read(LEVELDBLOG_HEADER_LEN)
        if len(header) == 0:
            return None
        if len(header) != LEVELDBLOG_HEADER_LEN:
            raise ValueError(
                f"Record header is {len(header)} bytes, expected {LEVELDBLOG_HEADER_LEN}"
            )
        checksum, dlength, dtype = struct.unpack("<IHB", header)
        self._index += LEVELDBLOG_HEADER_LEN
        data = self._fp.read(dlength)
        checksum_computed = zlib.crc32(data, self._crc[dtype]) & 0xFFFFFFFF
        if checksum != checksum_computed:
            raise ValueError("Record checksum is invalid, data may be corrupt")
        self._index += dlength
        return dtype, data

    def scan_data(self) -> Optional[bytes]:
        """Read and return the next complete record's data."""
        # Handle block padding
        offset = self._index % LEVELDBLOG_BLOCK_LEN
        space_left = LEVELDBLOG_BLOCK_LEN - offset
        if space_left < LEVELDBLOG_HEADER_LEN:
            pad = self._fp.read(space_left)
            self._index += space_left

        record = self._scan_record()
        if record is None:
            return None
        dtype, data = record

        if dtype == LEVELDBLOG_FULL:
            return data

        if dtype != LEVELDBLOG_FIRST:
            raise ValueError(f"Expected FIRST record type, got {dtype}")

        # Multi-part record
        while True:
            record = self._scan_record()
            if record is None:
                return None
            dtype, new_data = record
            if dtype == LEVELDBLOG_LAST:
                data += new_data
                break
            if dtype != LEVELDBLOG_MIDDLE:
                raise ValueError(f"Expected MIDDLE record type, got {dtype}")
            data += new_data
        return data

    def close(self) -> None:
        self._fp.close()


class DataStoreWriter:
    """Write records to a .wandb file (leveldb log format)."""

    def __init__(self, fname: str):
        self._fname = fname
        self._fp = open(fname, "wb")
        self._index = 0

        # Precompute CRC bases for each record type
        self._crc = [0] * (LEVELDBLOG_LAST + 1)
        for x in range(1, LEVELDBLOG_LAST + 1):
            self._crc[x] = zlib.crc32(_strtobytes(chr(x))) & 0xFFFFFFFF

        self._write_header()

    def _write_header(self) -> None:
        data = struct.pack(
            "<4sHB",
            LEVELDBLOG_HEADER_IDENT,
            LEVELDBLOG_HEADER_MAGIC,
            LEVELDBLOG_HEADER_VERSION,
        )
        self._fp.write(data)
        self._index += len(data)

    def _write_record(self, s: bytes, dtype: int = LEVELDBLOG_FULL) -> None:
        dlength = len(s)
        checksum = zlib.crc32(s, self._crc[dtype]) & 0xFFFFFFFF
        self._fp.write(struct.pack("<IHB", checksum, dlength, dtype))
        if dlength:
            self._fp.write(s)
        self._index += LEVELDBLOG_HEADER_LEN + len(s)

    def write_data(self, s: bytes) -> None:
        """Write a complete record, handling block boundaries."""
        offset = self._index % LEVELDBLOG_BLOCK_LEN
        space_left = LEVELDBLOG_BLOCK_LEN - offset
        data_used = 0
        data_left = len(s)

        # Pad to next block if not enough space for header
        if space_left < LEVELDBLOG_HEADER_LEN:
            pad = b"\x00" * space_left
            self._fp.write(pad)
            self._index += space_left
            space_left = LEVELDBLOG_BLOCK_LEN

        # Fits in single record
        if data_left + LEVELDBLOG_HEADER_LEN <= space_left:
            self._write_record(s)
        else:
            # Multi-part record
            data_room = space_left - LEVELDBLOG_HEADER_LEN
            self._write_record(s[:data_room], LEVELDBLOG_FIRST)
            data_used += data_room
            data_left -= data_room

            while data_left > LEVELDBLOG_DATA_LEN:
                self._write_record(
                    s[data_used : data_used + LEVELDBLOG_DATA_LEN], LEVELDBLOG_MIDDLE
                )
                data_used += LEVELDBLOG_DATA_LEN
                data_left -= LEVELDBLOG_DATA_LEN

            self._write_record(s[data_used:], LEVELDBLOG_LAST)

    def close(self) -> None:
        self._fp.close()


def fix_client_ids(wandb_file_path: str, dry_run: bool = False) -> dict:
    """Fix client IDs in a .wandb offline run file.

    Args:
        wandb_file_path: Path to the .wandb file
        dry_run: If True, only report what would be changed

    Returns:
        dict with statistics about changes made
    """
    if not os.path.exists(wandb_file_path):
        raise FileNotFoundError(f"File not found: {wandb_file_path}")

    if not wandb_file_path.endswith(".wandb"):
        raise ValueError(f"Expected .wandb file, got: {wandb_file_path}")

    # Track old -> new ID mappings for updating cross-references
    client_id_mapping: dict[str, str] = {}
    stats = {
        "artifacts_fixed": 0,
        "refs_updated": 0,
        "records_processed": 0,
    }

    # Read all records
    print(f"Scanning {wandb_file_path}...")
    reader = DataStoreReader(wandb_file_path)
    raw_records = []

    while True:
        data = reader.scan_data()
        if data is None:
            break
        raw_records.append(data)
        stats["records_processed"] += 1

    reader.close()
    print(f"  Found {stats['records_processed']} records")

    # Parse and fix records
    fixed_records = []
    for data in raw_records:
        pb = wandb_internal_pb2.Record()
        pb.ParseFromString(data)

        record_type = pb.WhichOneof("record_type")

        if record_type == "artifact":
            artifact = pb.artifact
            old_client_id = artifact.client_id
            old_seq_client_id = artifact.sequence_client_id

            if old_client_id:
                # Generate new unique IDs
                new_client_id = generate_id(128)
                new_seq_client_id = generate_id(128)

                client_id_mapping[old_client_id] = new_client_id
                if old_seq_client_id:
                    client_id_mapping[old_seq_client_id] = new_seq_client_id

                artifact.client_id = new_client_id
                artifact.sequence_client_id = new_seq_client_id
                stats["artifacts_fixed"] += 1

                print(f"  Artifact '{artifact.name}': regenerating client_id")
                if dry_run:
                    print(f"    Old: {old_client_id[:40]}...")
                    print(f"    New: {new_client_id[:40]}...")

        fixed_records.append(pb)

    # Second pass: update wandb-client-artifact:// references in manifests
    for pb in fixed_records:
        record_type = pb.WhichOneof("record_type")
        if record_type == "artifact":
            artifact = pb.artifact
            if artifact.manifest and artifact.manifest.contents:
                for entry in artifact.manifest.contents:
                    if entry.ref and entry.ref.startswith("wandb-client-artifact://"):
                        # Format: wandb-client-artifact://<client_id>/path
                        match = re.match(
                            r"wandb-client-artifact://([^/]+)/(.*)", entry.ref
                        )
                        if match:
                            ref_client_id = match.group(1)
                            path = match.group(2)
                            if ref_client_id in client_id_mapping:
                                new_ref = f"wandb-client-artifact://{client_id_mapping[ref_client_id]}/{path}"
                                if dry_run:
                                    print(f"  Updating ref in entry '{entry.path}'")
                                entry.ref = new_ref
                                stats["refs_updated"] += 1

    if dry_run:
        print(
            f"\nDry run complete. Would fix {stats['artifacts_fixed']} artifact(s) "
            f"and update {stats['refs_updated']} ref(s)."
        )
        return stats

    if stats["artifacts_fixed"] == 0:
        print("No artifacts found that need fixing.")
        return stats

    # Create backup
    backup_path = wandb_file_path + ".backup"
    print(f"Creating backup: {backup_path}")
    shutil.copy2(wandb_file_path, backup_path)

    # Write fixed records
    temp_path = wandb_file_path + ".tmp"
    print("Writing fixed records...")
    writer = DataStoreWriter(temp_path)

    for pb in fixed_records:
        serialized = pb.SerializeToString()
        writer.write_data(serialized)

    writer.close()

    # Replace original with fixed file
    os.replace(temp_path, wandb_file_path)

    print(
        f"\nDone! Fixed {stats['artifacts_fixed']} artifact(s), "
        f"updated {stats['refs_updated']} ref(s)."
    )
    print(f"Backup saved to: {backup_path}")

    return stats


def main():
    parser = argparse.ArgumentParser(
        description="Fix invalid client IDs in offline wandb run files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "wandb_file",
        nargs="?",
        help="Path to the .wandb file (e.g., ./wandb/offline-run-.../run-xxx.wandb)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only report what would be changed, don't modify files",
    )
    parser.add_argument(
        "--dir",
        metavar="WANDB_DIR",
        help="Process all offline runs in a wandb directory (e.g., ./wandb)",
    )

    args = parser.parse_args()

    if not args.wandb_file and not args.dir:
        parser.error("Either wandb_file or --dir is required")

    if args.dir:
        # Process all offline runs in directory
        wandb_dir = args.dir
        if not os.path.isdir(wandb_dir):
            print(f"Error: {wandb_dir} is not a directory", file=sys.stderr)
            sys.exit(1)

        total_stats = {"artifacts_fixed": 0, "refs_updated": 0, "files_processed": 0}

        for entry in sorted(os.listdir(wandb_dir)):
            if entry.startswith("offline-run-"):
                run_dir = os.path.join(wandb_dir, entry)
                if os.path.isdir(run_dir):
                    for fname in os.listdir(run_dir):
                        if fname.endswith(".wandb") and not fname.endswith(
                            (".synced", ".backup", ".tmp")
                        ):
                            wandb_file = os.path.join(run_dir, fname)
                            print(f"\n{'='*60}")
                            print(f"Processing: {wandb_file}")
                            print("=" * 60)
                            try:
                                stats = fix_client_ids(wandb_file, dry_run=args.dry_run)
                                total_stats["artifacts_fixed"] += stats[
                                    "artifacts_fixed"
                                ]
                                total_stats["refs_updated"] += stats["refs_updated"]
                                total_stats["files_processed"] += 1
                            except Exception as e:
                                print(f"Error: {e}", file=sys.stderr)

        print(f"\n{'='*60}")
        print("Summary")
        print("=" * 60)
        print(f"Files processed: {total_stats['files_processed']}")
        print(f"Total artifacts fixed: {total_stats['artifacts_fixed']}")
        print(f"Total refs updated: {total_stats['refs_updated']}")
    else:
        try:
            fix_client_ids(args.wandb_file, dry_run=args.dry_run)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
